name: Deploy Docs Workflow
on:
  push:
    branches:
      - master
jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Packages
        run: yarn
        working-directory: website

      - name: Publish gh-pages
        run: |
          git config --global user.name  "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"
          echo "machine github.com login ${{ secrets.USERNAME }} password ${{ secrets.TOKEN }}" > ~/.netrc
          yarn build
          GIT_USER=${{ secrets.USERNAME }} USE_SSH=true yarn deploy
        working-directory: website
        env:
          GIT_USER: ${{ secrets.USERNAME }}
          CURRENT_BRANCH: master
